package enums;

public enum Location {
	BREAKERS_BRIDGE,
	BRONZE_GATE,
	CAVE_OF_EMBERS,
	CAVE_OF_SHADOWS,
	CLIFFS_OF_ABANDON,
	COPPER_GATE,
	CORAL_PALACE,
	CRIMSON_FOREST,
	DUNES_OF_DECEPTION,
	FOOLS_LANDING,
	GOLD_GATE,
	HOWLING_GARDEN,
	IRON_GATE,
	LOST_LAGOON,
	MISTY_MARSH,
	OBSERVATORY,
	PHANTOM_ROCK,
	SILVER_GATE,
	TEMPLE_OF_THE_MOON,
	TEMPLE_OF_THE_SUN,
	TIDAL_PALACE,
	TWILIGHT_HOLLOW,
	WATCHTOWER,
	WHISPERING_GARDEN
}
